services:

  app:
    container_name: node_app

    build:
      context: .
      dockerfile: Dockerfile

    # docker compose --profile development up
    # profiles:
    #   - development

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: development

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      - pg

  pg:
    container_name: postgres

    image: postgres:16

    ports:
      - "5433:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

    volumes:
      - pgVolume:/var/lib/postgresql/data

volumes:
  pgVolume: